/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ActionSendKubectlInput struct for ActionSendKubectlInput
type ActionSendKubectlInput struct {
	Properties *ActionSendKubectlInputProperties `json:"properties,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewActionSendKubectlInput instantiates a new ActionSendKubectlInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionSendKubectlInput() *ActionSendKubectlInput {
	this := ActionSendKubectlInput{}
	return &this
}

// NewActionSendKubectlInputWithDefaults instantiates a new ActionSendKubectlInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionSendKubectlInputWithDefaults() *ActionSendKubectlInput {
	this := ActionSendKubectlInput{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ActionSendKubectlInput) GetProperties() ActionSendKubectlInputProperties {
	if o == nil || o.Properties == nil {
		var ret ActionSendKubectlInputProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionSendKubectlInput) GetPropertiesOk() (*ActionSendKubectlInputProperties, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ActionSendKubectlInput) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given ActionSendKubectlInputProperties and assigns it to the Properties field.
func (o *ActionSendKubectlInput) SetProperties(v ActionSendKubectlInputProperties) {
	o.Properties = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ActionSendKubectlInput) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionSendKubectlInput) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ActionSendKubectlInput) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ActionSendKubectlInput) SetType(v string) {
	o.Type = &v
}

func (o ActionSendKubectlInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableActionSendKubectlInput struct {
	value *ActionSendKubectlInput
	isSet bool
}

func (v NullableActionSendKubectlInput) Get() *ActionSendKubectlInput {
	return v.value
}

func (v *NullableActionSendKubectlInput) Set(val *ActionSendKubectlInput) {
	v.value = val
	v.isSet = true
}

func (v NullableActionSendKubectlInput) IsSet() bool {
	return v.isSet
}

func (v *NullableActionSendKubectlInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionSendKubectlInput(val *ActionSendKubectlInput) *NullableActionSendKubectlInput {
	return &NullableActionSendKubectlInput{value: val, isSet: true}
}

func (v NullableActionSendKubectlInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionSendKubectlInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


