/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ActionStopStats struct for ActionStopStats
type ActionStopStats struct {
	Description *string `json:"description,omitempty"`
	Links *[]ActionRunStatsLinks `json:"links,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewActionStopStats instantiates a new ActionStopStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionStopStats() *ActionStopStats {
	this := ActionStopStats{}
	return &this
}

// NewActionStopStatsWithDefaults instantiates a new ActionStopStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionStopStatsWithDefaults() *ActionStopStats {
	this := ActionStopStats{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ActionStopStats) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionStopStats) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ActionStopStats) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ActionStopStats) SetDescription(v string) {
	o.Description = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ActionStopStats) GetLinks() []ActionRunStatsLinks {
	if o == nil || o.Links == nil {
		var ret []ActionRunStatsLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionStopStats) GetLinksOk() (*[]ActionRunStatsLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ActionStopStats) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []ActionRunStatsLinks and assigns it to the Links field.
func (o *ActionStopStats) SetLinks(v []ActionRunStatsLinks) {
	o.Links = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ActionStopStats) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionStopStats) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ActionStopStats) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ActionStopStats) SetTitle(v string) {
	o.Title = &v
}

func (o ActionStopStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableActionStopStats struct {
	value *ActionStopStats
	isSet bool
}

func (v NullableActionStopStats) Get() *ActionStopStats {
	return v.value
}

func (v *NullableActionStopStats) Set(val *ActionStopStats) {
	v.value = val
	v.isSet = true
}

func (v NullableActionStopStats) IsSet() bool {
	return v.isSet
}

func (v *NullableActionStopStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionStopStats(val *ActionStopStats) *NullableActionStopStats {
	return &NullableActionStopStats{value: val, isSet: true}
}

func (v NullableActionStopStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionStopStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


