/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListClustersResponseElement2 struct for ListClustersResponseElement2
type ListClustersResponseElement2 struct {
	Description *string `json:"description,omitempty"`
	Id *string `json:"id,omitempty"`
	Properties *ListClustersResponseElement1Properties `json:"properties,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewListClustersResponseElement2 instantiates a new ListClustersResponseElement2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListClustersResponseElement2() *ListClustersResponseElement2 {
	this := ListClustersResponseElement2{}
	return &this
}

// NewListClustersResponseElement2WithDefaults instantiates a new ListClustersResponseElement2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListClustersResponseElement2WithDefaults() *ListClustersResponseElement2 {
	this := ListClustersResponseElement2{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ListClustersResponseElement2) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListClustersResponseElement2) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ListClustersResponseElement2) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ListClustersResponseElement2) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListClustersResponseElement2) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListClustersResponseElement2) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListClustersResponseElement2) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ListClustersResponseElement2) SetId(v string) {
	o.Id = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ListClustersResponseElement2) GetProperties() ListClustersResponseElement1Properties {
	if o == nil || o.Properties == nil {
		var ret ListClustersResponseElement1Properties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListClustersResponseElement2) GetPropertiesOk() (*ListClustersResponseElement1Properties, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ListClustersResponseElement2) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given ListClustersResponseElement1Properties and assigns it to the Properties field.
func (o *ListClustersResponseElement2) SetProperties(v ListClustersResponseElement1Properties) {
	o.Properties = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ListClustersResponseElement2) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListClustersResponseElement2) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ListClustersResponseElement2) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ListClustersResponseElement2) SetTitle(v string) {
	o.Title = &v
}

func (o ListClustersResponseElement2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableListClustersResponseElement2 struct {
	value *ListClustersResponseElement2
	isSet bool
}

func (v NullableListClustersResponseElement2) Get() *ListClustersResponseElement2 {
	return v.value
}

func (v *NullableListClustersResponseElement2) Set(val *ListClustersResponseElement2) {
	v.value = val
	v.isSet = true
}

func (v NullableListClustersResponseElement2) IsSet() bool {
	return v.isSet
}

func (v *NullableListClustersResponseElement2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListClustersResponseElement2(val *ListClustersResponseElement2) *NullableListClustersResponseElement2 {
	return &NullableListClustersResponseElement2{value: val, isSet: true}
}

func (v NullableListClustersResponseElement2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListClustersResponseElement2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


