/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateCluster struct for CreateCluster
type CreateCluster struct {
	Description *string `json:"description,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewCreateCluster instantiates a new CreateCluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCluster() *CreateCluster {
	this := CreateCluster{}
	return &this
}

// NewCreateClusterWithDefaults instantiates a new CreateCluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterWithDefaults() *CreateCluster {
	this := CreateCluster{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateCluster) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCluster) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateCluster) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateCluster) SetDescription(v string) {
	o.Description = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateCluster) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCluster) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateCluster) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateCluster) SetTitle(v string) {
	o.Title = &v
}

func (o CreateCluster) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCluster struct {
	value *CreateCluster
	isSet bool
}

func (v NullableCreateCluster) Get() *CreateCluster {
	return v.value
}

func (v *NullableCreateCluster) Set(val *CreateCluster) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCluster(val *CreateCluster) *NullableCreateCluster {
	return &NullableCreateCluster{value: val, isSet: true}
}

func (v NullableCreateCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


