/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ActionResponseElement2 struct for ActionResponseElement2
type ActionResponseElement2 struct {
	Delay *ActionResponseElement2Delay `json:"delay,omitempty"`
}

// NewActionResponseElement2 instantiates a new ActionResponseElement2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionResponseElement2() *ActionResponseElement2 {
	this := ActionResponseElement2{}
	return &this
}

// NewActionResponseElement2WithDefaults instantiates a new ActionResponseElement2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionResponseElement2WithDefaults() *ActionResponseElement2 {
	this := ActionResponseElement2{}
	return &this
}

// GetDelay returns the Delay field value if set, zero value otherwise.
func (o *ActionResponseElement2) GetDelay() ActionResponseElement2Delay {
	if o == nil || o.Delay == nil {
		var ret ActionResponseElement2Delay
		return ret
	}
	return *o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionResponseElement2) GetDelayOk() (*ActionResponseElement2Delay, bool) {
	if o == nil || o.Delay == nil {
		return nil, false
	}
	return o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *ActionResponseElement2) HasDelay() bool {
	if o != nil && o.Delay != nil {
		return true
	}

	return false
}

// SetDelay gets a reference to the given ActionResponseElement2Delay and assigns it to the Delay field.
func (o *ActionResponseElement2) SetDelay(v ActionResponseElement2Delay) {
	o.Delay = &v
}

func (o ActionResponseElement2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Delay != nil {
		toSerialize["delay"] = o.Delay
	}
	return json.Marshal(toSerialize)
}

type NullableActionResponseElement2 struct {
	value *ActionResponseElement2
	isSet bool
}

func (v NullableActionResponseElement2) Get() *ActionResponseElement2 {
	return v.value
}

func (v *NullableActionResponseElement2) Set(val *ActionResponseElement2) {
	v.value = val
	v.isSet = true
}

func (v NullableActionResponseElement2) IsSet() bool {
	return v.isSet
}

func (v *NullableActionResponseElement2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionResponseElement2(val *ActionResponseElement2) *NullableActionResponseElement2 {
	return &NullableActionResponseElement2{value: val, isSet: true}
}

func (v NullableActionResponseElement2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionResponseElement2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


