/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LabelListElementRelations struct for LabelListElementRelations
type LabelListElementRelations struct {
	Data *[]LabelRelationElement1 `json:"data,omitempty"`
	Paging *map[string]interface{} `json:"paging,omitempty"`
}

// NewLabelListElementRelations instantiates a new LabelListElementRelations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelListElementRelations() *LabelListElementRelations {
	this := LabelListElementRelations{}
	return &this
}

// NewLabelListElementRelationsWithDefaults instantiates a new LabelListElementRelations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelListElementRelationsWithDefaults() *LabelListElementRelations {
	this := LabelListElementRelations{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LabelListElementRelations) GetData() []LabelRelationElement1 {
	if o == nil || o.Data == nil {
		var ret []LabelRelationElement1
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelListElementRelations) GetDataOk() (*[]LabelRelationElement1, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LabelListElementRelations) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []LabelRelationElement1 and assigns it to the Data field.
func (o *LabelListElementRelations) SetData(v []LabelRelationElement1) {
	o.Data = &v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *LabelListElementRelations) GetPaging() map[string]interface{} {
	if o == nil || o.Paging == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelListElementRelations) GetPagingOk() (*map[string]interface{}, bool) {
	if o == nil || o.Paging == nil {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *LabelListElementRelations) HasPaging() bool {
	if o != nil && o.Paging != nil {
		return true
	}

	return false
}

// SetPaging gets a reference to the given map[string]interface{} and assigns it to the Paging field.
func (o *LabelListElementRelations) SetPaging(v map[string]interface{}) {
	o.Paging = &v
}

func (o LabelListElementRelations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Paging != nil {
		toSerialize["paging"] = o.Paging
	}
	return json.Marshal(toSerialize)
}

type NullableLabelListElementRelations struct {
	value *LabelListElementRelations
	isSet bool
}

func (v NullableLabelListElementRelations) Get() *LabelListElementRelations {
	return v.value
}

func (v *NullableLabelListElementRelations) Set(val *LabelListElementRelations) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelListElementRelations) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelListElementRelations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelListElementRelations(val *LabelListElementRelations) *NullableLabelListElementRelations {
	return &NullableLabelListElementRelations{value: val, isSet: true}
}

func (v NullableLabelListElementRelations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelListElementRelations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


