/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CredentialsResponseThing struct for CredentialsResponseThing
type CredentialsResponseThing struct {
	Collection *[]CredentialsThing `json:"collection,omitempty"`
}

// NewCredentialsResponseThing instantiates a new CredentialsResponseThing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsResponseThing() *CredentialsResponseThing {
	this := CredentialsResponseThing{}
	return &this
}

// NewCredentialsResponseThingWithDefaults instantiates a new CredentialsResponseThing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsResponseThingWithDefaults() *CredentialsResponseThing {
	this := CredentialsResponseThing{}
	return &this
}

// GetCollection returns the Collection field value if set, zero value otherwise.
func (o *CredentialsResponseThing) GetCollection() []CredentialsThing {
	if o == nil || o.Collection == nil {
		var ret []CredentialsThing
		return ret
	}
	return *o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsResponseThing) GetCollectionOk() (*[]CredentialsThing, bool) {
	if o == nil || o.Collection == nil {
		return nil, false
	}
	return o.Collection, true
}

// HasCollection returns a boolean if a field has been set.
func (o *CredentialsResponseThing) HasCollection() bool {
	if o != nil && o.Collection != nil {
		return true
	}

	return false
}

// SetCollection gets a reference to the given []CredentialsThing and assigns it to the Collection field.
func (o *CredentialsResponseThing) SetCollection(v []CredentialsThing) {
	o.Collection = &v
}

func (o CredentialsResponseThing) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Collection != nil {
		toSerialize["collection"] = o.Collection
	}
	return json.Marshal(toSerialize)
}

type NullableCredentialsResponseThing struct {
	value *CredentialsResponseThing
	isSet bool
}

func (v NullableCredentialsResponseThing) Get() *CredentialsResponseThing {
	return v.value
}

func (v *NullableCredentialsResponseThing) Set(val *CredentialsResponseThing) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsResponseThing) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsResponseThing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsResponseThing(val *CredentialsResponseThing) *NullableCredentialsResponseThing {
	return &NullableCredentialsResponseThing{value: val, isSet: true}
}

func (v NullableCredentialsResponseThing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsResponseThing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


