/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ModelsResourcesResponseShow struct for ModelsResourcesResponseShow
type ModelsResourcesResponseShow struct {
	Description *string `json:"description,omitempty"`
	File *string `json:"file,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Params *[]string `json:"params,omitempty"`
	ParamsId *string `json:"params_id,omitempty"`
}

// NewModelsResourcesResponseShow instantiates a new ModelsResourcesResponseShow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResourcesResponseShow() *ModelsResourcesResponseShow {
	this := ModelsResourcesResponseShow{}
	return &this
}

// NewModelsResourcesResponseShowWithDefaults instantiates a new ModelsResourcesResponseShow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResourcesResponseShowWithDefaults() *ModelsResourcesResponseShow {
	this := ModelsResourcesResponseShow{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsResourcesResponseShow) SetDescription(v string) {
	o.Description = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetFile() string {
	if o == nil || o.File == nil {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetFileOk() (*string, bool) {
	if o == nil || o.File == nil {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasFile() bool {
	if o != nil && o.File != nil {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *ModelsResourcesResponseShow) SetFile(v string) {
	o.File = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsResourcesResponseShow) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsResourcesResponseShow) SetName(v string) {
	o.Name = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetParams() []string {
	if o == nil || o.Params == nil {
		var ret []string
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetParamsOk() (*[]string, bool) {
	if o == nil || o.Params == nil {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasParams() bool {
	if o != nil && o.Params != nil {
		return true
	}

	return false
}

// SetParams gets a reference to the given []string and assigns it to the Params field.
func (o *ModelsResourcesResponseShow) SetParams(v []string) {
	o.Params = &v
}

// GetParamsId returns the ParamsId field value if set, zero value otherwise.
func (o *ModelsResourcesResponseShow) GetParamsId() string {
	if o == nil || o.ParamsId == nil {
		var ret string
		return ret
	}
	return *o.ParamsId
}

// GetParamsIdOk returns a tuple with the ParamsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseShow) GetParamsIdOk() (*string, bool) {
	if o == nil || o.ParamsId == nil {
		return nil, false
	}
	return o.ParamsId, true
}

// HasParamsId returns a boolean if a field has been set.
func (o *ModelsResourcesResponseShow) HasParamsId() bool {
	if o != nil && o.ParamsId != nil {
		return true
	}

	return false
}

// SetParamsId gets a reference to the given string and assigns it to the ParamsId field.
func (o *ModelsResourcesResponseShow) SetParamsId(v string) {
	o.ParamsId = &v
}

func (o ModelsResourcesResponseShow) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.File != nil {
		toSerialize["file"] = o.File
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	if o.ParamsId != nil {
		toSerialize["params_id"] = o.ParamsId
	}
	return json.Marshal(toSerialize)
}

type NullableModelsResourcesResponseShow struct {
	value *ModelsResourcesResponseShow
	isSet bool
}

func (v NullableModelsResourcesResponseShow) Get() *ModelsResourcesResponseShow {
	return v.value
}

func (v *NullableModelsResourcesResponseShow) Set(val *ModelsResourcesResponseShow) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResourcesResponseShow) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResourcesResponseShow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResourcesResponseShow(val *ModelsResourcesResponseShow) *NullableModelsResourcesResponseShow {
	return &NullableModelsResourcesResponseShow{value: val, isSet: true}
}

func (v NullableModelsResourcesResponseShow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResourcesResponseShow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


