/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ModelsResourcesSetParams struct for ModelsResourcesSetParams
type ModelsResourcesSetParams struct {
	Params *[]string `json:"params,omitempty"`
}

// NewModelsResourcesSetParams instantiates a new ModelsResourcesSetParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResourcesSetParams() *ModelsResourcesSetParams {
	this := ModelsResourcesSetParams{}
	return &this
}

// NewModelsResourcesSetParamsWithDefaults instantiates a new ModelsResourcesSetParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResourcesSetParamsWithDefaults() *ModelsResourcesSetParams {
	this := ModelsResourcesSetParams{}
	return &this
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ModelsResourcesSetParams) GetParams() []string {
	if o == nil || o.Params == nil {
		var ret []string
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesSetParams) GetParamsOk() (*[]string, bool) {
	if o == nil || o.Params == nil {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ModelsResourcesSetParams) HasParams() bool {
	if o != nil && o.Params != nil {
		return true
	}

	return false
}

// SetParams gets a reference to the given []string and assigns it to the Params field.
func (o *ModelsResourcesSetParams) SetParams(v []string) {
	o.Params = &v
}

func (o ModelsResourcesSetParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	return json.Marshal(toSerialize)
}

type NullableModelsResourcesSetParams struct {
	value *ModelsResourcesSetParams
	isSet bool
}

func (v NullableModelsResourcesSetParams) Get() *ModelsResourcesSetParams {
	return v.value
}

func (v *NullableModelsResourcesSetParams) Set(val *ModelsResourcesSetParams) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResourcesSetParams) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResourcesSetParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResourcesSetParams(val *ModelsResourcesSetParams) *NullableModelsResourcesSetParams {
	return &NullableModelsResourcesSetParams{value: val, isSet: true}
}

func (v NullableModelsResourcesSetParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResourcesSetParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


