/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EventResponse1 struct for EventResponse1
type EventResponse1 struct {
	HighCPU *EventResponse1HighCPU `json:"highCPU,omitempty"`
}

// NewEventResponse1 instantiates a new EventResponse1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventResponse1() *EventResponse1 {
	this := EventResponse1{}
	return &this
}

// NewEventResponse1WithDefaults instantiates a new EventResponse1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventResponse1WithDefaults() *EventResponse1 {
	this := EventResponse1{}
	return &this
}

// GetHighCPU returns the HighCPU field value if set, zero value otherwise.
func (o *EventResponse1) GetHighCPU() EventResponse1HighCPU {
	if o == nil || o.HighCPU == nil {
		var ret EventResponse1HighCPU
		return ret
	}
	return *o.HighCPU
}

// GetHighCPUOk returns a tuple with the HighCPU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventResponse1) GetHighCPUOk() (*EventResponse1HighCPU, bool) {
	if o == nil || o.HighCPU == nil {
		return nil, false
	}
	return o.HighCPU, true
}

// HasHighCPU returns a boolean if a field has been set.
func (o *EventResponse1) HasHighCPU() bool {
	if o != nil && o.HighCPU != nil {
		return true
	}

	return false
}

// SetHighCPU gets a reference to the given EventResponse1HighCPU and assigns it to the HighCPU field.
func (o *EventResponse1) SetHighCPU(v EventResponse1HighCPU) {
	o.HighCPU = &v
}

func (o EventResponse1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.HighCPU != nil {
		toSerialize["highCPU"] = o.HighCPU
	}
	return json.Marshal(toSerialize)
}

type NullableEventResponse1 struct {
	value *EventResponse1
	isSet bool
}

func (v NullableEventResponse1) Get() *EventResponse1 {
	return v.value
}

func (v *NullableEventResponse1) Set(val *EventResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableEventResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableEventResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventResponse1(val *EventResponse1) *NullableEventResponse1 {
	return &NullableEventResponse1{value: val, isSet: true}
}

func (v NullableEventResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


