/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ModelsBuildConfigResponse struct for ModelsBuildConfigResponse
type ModelsBuildConfigResponse struct {
	Description *string `json:"description,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Resources *[]ModelsResourcesFullJsonCustomBinder `json:"resources,omitempty"`
}

// NewModelsBuildConfigResponse instantiates a new ModelsBuildConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsBuildConfigResponse() *ModelsBuildConfigResponse {
	this := ModelsBuildConfigResponse{}
	return &this
}

// NewModelsBuildConfigResponseWithDefaults instantiates a new ModelsBuildConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsBuildConfigResponseWithDefaults() *ModelsBuildConfigResponse {
	this := ModelsBuildConfigResponse{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsBuildConfigResponse) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBuildConfigResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsBuildConfigResponse) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsBuildConfigResponse) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsBuildConfigResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBuildConfigResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsBuildConfigResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsBuildConfigResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsBuildConfigResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBuildConfigResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsBuildConfigResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsBuildConfigResponse) SetName(v string) {
	o.Name = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *ModelsBuildConfigResponse) GetResources() []ModelsResourcesFullJsonCustomBinder {
	if o == nil || o.Resources == nil {
		var ret []ModelsResourcesFullJsonCustomBinder
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBuildConfigResponse) GetResourcesOk() (*[]ModelsResourcesFullJsonCustomBinder, bool) {
	if o == nil || o.Resources == nil {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *ModelsBuildConfigResponse) HasResources() bool {
	if o != nil && o.Resources != nil {
		return true
	}

	return false
}

// SetResources gets a reference to the given []ModelsResourcesFullJsonCustomBinder and assigns it to the Resources field.
func (o *ModelsBuildConfigResponse) SetResources(v []ModelsResourcesFullJsonCustomBinder) {
	o.Resources = &v
}

func (o ModelsBuildConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Resources != nil {
		toSerialize["resources"] = o.Resources
	}
	return json.Marshal(toSerialize)
}

type NullableModelsBuildConfigResponse struct {
	value *ModelsBuildConfigResponse
	isSet bool
}

func (v NullableModelsBuildConfigResponse) Get() *ModelsBuildConfigResponse {
	return v.value
}

func (v *NullableModelsBuildConfigResponse) Set(val *ModelsBuildConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsBuildConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsBuildConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsBuildConfigResponse(val *ModelsBuildConfigResponse) *NullableModelsBuildConfigResponse {
	return &NullableModelsBuildConfigResponse{value: val, isSet: true}
}

func (v NullableModelsBuildConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsBuildConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


