/*
 * Accounts & Users Service - Public API
 *
 * IN PROGRESS->This is the guide to use the different endpoints to manage the clusters.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ModelsResourcesResponseList struct for ModelsResourcesResponseList
type ModelsResourcesResponseList struct {
	Description *string `json:"description,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Params *[]string `json:"params,omitempty"`
	ParamsId *string `json:"params_id,omitempty"`
}

// NewModelsResourcesResponseList instantiates a new ModelsResourcesResponseList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResourcesResponseList() *ModelsResourcesResponseList {
	this := ModelsResourcesResponseList{}
	return &this
}

// NewModelsResourcesResponseListWithDefaults instantiates a new ModelsResourcesResponseList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResourcesResponseListWithDefaults() *ModelsResourcesResponseList {
	this := ModelsResourcesResponseList{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModelsResourcesResponseList) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseList) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModelsResourcesResponseList) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModelsResourcesResponseList) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsResourcesResponseList) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseList) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsResourcesResponseList) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsResourcesResponseList) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsResourcesResponseList) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseList) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsResourcesResponseList) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsResourcesResponseList) SetName(v string) {
	o.Name = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ModelsResourcesResponseList) GetParams() []string {
	if o == nil || o.Params == nil {
		var ret []string
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseList) GetParamsOk() (*[]string, bool) {
	if o == nil || o.Params == nil {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ModelsResourcesResponseList) HasParams() bool {
	if o != nil && o.Params != nil {
		return true
	}

	return false
}

// SetParams gets a reference to the given []string and assigns it to the Params field.
func (o *ModelsResourcesResponseList) SetParams(v []string) {
	o.Params = &v
}

// GetParamsId returns the ParamsId field value if set, zero value otherwise.
func (o *ModelsResourcesResponseList) GetParamsId() string {
	if o == nil || o.ParamsId == nil {
		var ret string
		return ret
	}
	return *o.ParamsId
}

// GetParamsIdOk returns a tuple with the ParamsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsResourcesResponseList) GetParamsIdOk() (*string, bool) {
	if o == nil || o.ParamsId == nil {
		return nil, false
	}
	return o.ParamsId, true
}

// HasParamsId returns a boolean if a field has been set.
func (o *ModelsResourcesResponseList) HasParamsId() bool {
	if o != nil && o.ParamsId != nil {
		return true
	}

	return false
}

// SetParamsId gets a reference to the given string and assigns it to the ParamsId field.
func (o *ModelsResourcesResponseList) SetParamsId(v string) {
	o.ParamsId = &v
}

func (o ModelsResourcesResponseList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	if o.ParamsId != nil {
		toSerialize["params_id"] = o.ParamsId
	}
	return json.Marshal(toSerialize)
}

type NullableModelsResourcesResponseList struct {
	value *ModelsResourcesResponseList
	isSet bool
}

func (v NullableModelsResourcesResponseList) Get() *ModelsResourcesResponseList {
	return v.value
}

func (v *NullableModelsResourcesResponseList) Set(val *ModelsResourcesResponseList) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResourcesResponseList) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResourcesResponseList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResourcesResponseList(val *ModelsResourcesResponseList) *NullableModelsResourcesResponseList {
	return &NullableModelsResourcesResponseList{value: val, isSet: true}
}

func (v NullableModelsResourcesResponseList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResourcesResponseList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


